namespace DolCon.Models;

using Enums;

public record LocationType(
    string Type,
    Rarity Rarity,
    int? Biome,
    bool IsBurgLocation,
    LocationSize Size,
    bool AllowMultiple,
    bool NeedsPort,
    bool NeedsCitadel,
    bool NeedsPlaza,
    bool NeedsShanty,
    bool NeedsTemple,
    bool NeedsWalls,
    bool NeedsCityOfLight,
    Tag[] Goods,
    Service[] Services
);

public static class LocationTypes
{
    public static List<LocationType> Types { get; } = new List<LocationType>
    {
        new LocationType(
            "abandoned mine",
            Rarity.uncommon,
            null,
            false,
            LocationSize.medium,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            Array.Empty<Tag>(),
            Array.Empty<Service>()
        ),
        new LocationType(
            "abandoned temple",
            Rarity.rare,
            null,
            false,
            LocationSize.small,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            Array.Empty<Tag>(),
            Array.Empty<Service>()
        ),
        new LocationType(
            "abandoned wizard tower",
            Rarity.epic,
            null,
            false,
            LocationSize.medium,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            Array.Empty<Tag>(),
            Array.Empty<Service>()
        ),
        new LocationType(
            "ancient battlefield",
            Rarity.epic,
            null,
            false,
            LocationSize.medium,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            Array.Empty<Tag>(),
            Array.Empty<Service>()
        ),
        new LocationType(
            "ancient ruins",
            Rarity.uncommon,
            null,
            false,
            LocationSize.medium,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            Array.Empty<Tag>(),
            Array.Empty<Service>()
        ),
        new LocationType(
            "ancient tomb",
            Rarity.rare,
            null,
            false,
            LocationSize.medium,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            Array.Empty<Tag>(),
            Array.Empty<Service>()
        ),
        new LocationType(
            "arena",
            Rarity.uncommon,
            null,
            true,
            LocationSize.unexplorable,
            false,
            false,
            false,
            true,
            false,
            false,
            false,
            false,
            Array.Empty<Tag>(),
            new[] { Service.combat, Service.entertainment }
        ),
        new LocationType(
            "armory",
            Rarity.uncommon,
            null,
            true,
            LocationSize.unexplorable,
            true,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            new[]
            {
                new Tag("Light Armor", TagType.armor),
                new Tag("Medium Armor", TagType.armor),
                new Tag("Heavy Armor", TagType.armor),
                new Tag("Shield", TagType.armor),
                new Tag("Light Weapon", TagType.weapon),
                new Tag("Medium Weapon", TagType.weapon),
                new Tag("Heavy Weapon", TagType.weapon),
                new Tag("Ammunition", TagType.weapon),
            },
            new[] { Service.repair }
        ),
        new LocationType(
            "bandit camp",
            Rarity.rare,
            null,
            false,
            LocationSize.small,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            Array.Empty<Tag>(),
            Array.Empty<Service>()
        ),
        new LocationType(
            "tavern",
            Rarity.common,
            null,
            true,
            LocationSize.unexplorable,
            true,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            new[]
            {
                new Tag("Snack", TagType.food),
                new Tag("Meal", TagType.food),
                new Tag("Spirits", TagType.food)
            },
            new[] { Service.drinks, Service.food }
        ),
        new LocationType(
            "blacksmith",
            Rarity.uncommon,
            null,
            true,
            LocationSize.unexplorable,
            true,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            Array.Empty<Tag>(),
            new[] { Service.repair, Service.upgrade }
        ),
        new LocationType(
            "castle",
            Rarity.rare,
            null,
            true,
            LocationSize.medium,
            false,
            false,
            true,
            false,
            false,
            false,
            false,
            false,
            Array.Empty<Tag>(),
            Array.Empty<Service>()
        ),
        new LocationType(
            "cave",
            Rarity.uncommon,
            null,
            false,
            LocationSize.large,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            Array.Empty<Tag>(),
            Array.Empty<Service>()
        ),
        new LocationType(
            "cemetery",
            Rarity.uncommon,
            null,
            true,
            LocationSize.medium,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            Array.Empty<Tag>(),
            Array.Empty<Service>()
        ),
        new LocationType(
            "colosseum",
            Rarity.epic,
            null,
            true,
            LocationSize.unexplorable,
            false,
            false,
            false,
            true,
            false,
            false,
            false,
            false,
            Array.Empty<Tag>(),
            new[] { Service.combat, Service.entertainment }
        ),
        new LocationType(
            "crypt",
            Rarity.rare,
            null,
            false,
            LocationSize.large,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            Array.Empty<Tag>(),
            Array.Empty<Service>()
        ),
        new LocationType(
            "dungeon",
            Rarity.rare,
            null,
            true,
            LocationSize.large,
            false,
            false,
            false,
            false,
            true,
            false,
            true,
            false,
            Array.Empty<Tag>(),
            Array.Empty<Service>()
        ),
        new LocationType(
            "farm",
            Rarity.common,
            null,
            false,
            LocationSize.unexplorable,
            true,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            new[]
            {
                new Tag("Snack", TagType.food),
            },
            new[] { Service.food }
        ),
        new LocationType(
            "fort",
            Rarity.rare,
            null,
            false,
            LocationSize.medium,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            Array.Empty<Tag>(),
            new[] { Service.food, Service.combat, Service.lodging, Service.repair }
        ),
        new LocationType(
            "garden",
            Rarity.uncommon,
            null,
            true,
            LocationSize.small,
            false,
            false,
            false,
            true,
            false,
            false,
            false,
            false,
            new[]
            {
                new Tag("Snack", TagType.food),
                new Tag("Meal", TagType.food),
            },
            new[] { Service.food }
        ),
        new LocationType(
            "general store",
            Rarity.common,
            null,
            true,
            LocationSize.unexplorable,
            true,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            new[]
            {
                new Tag("Snack", TagType.food),
                new Tag("Light Armor", TagType.armor),
                new Tag("Light Weapon", TagType.weapon),
                new Tag("Ammunition", TagType.weapon),
                new Tag("Adventure Gear", TagType.generalGoods),
                new Tag("Tools", TagType.generalGoods),
            },
            Array.Empty<Service>()
        ),
        new LocationType(
            "inn",
            Rarity.uncommon,
            null,
            true,
            LocationSize.unexplorable,
            true,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            new[]
            {
                new Tag("Snack", TagType.food),
                new Tag("Meal", TagType.food),
                new Tag("Spirits", TagType.food)
            },
            new[] { Service.food, Service.lodging }
        ),
        new LocationType(
            "library",
            Rarity.rare,
            null,
            true,
            LocationSize.small,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            Array.Empty<Tag>(),
            Array.Empty<Service>()
        ),
        new LocationType(
            "mine",
            Rarity.uncommon,
            null,
            false,
            LocationSize.large,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            Array.Empty<Tag>(),
            Array.Empty<Service>()
        ),
        new LocationType(
            "pier",
            Rarity.common,
            null,
            true,
            LocationSize.unexplorable,
            false,
            true,
            false,
            false,
            false,
            false,
            false,
            false,
            Array.Empty<Tag>(),
            new[] { Service.ships }
        ),
        new LocationType(
            "dock",
            Rarity.uncommon,
            null,
            true,
            LocationSize.unexplorable,
            false,
            true,
            false,
            false,
            false,
            false,
            false,
            false,
            Array.Empty<Tag>(),
            new[] { Service.ships }
        ),
        new LocationType(
            "harbor",
            Rarity.rare,
            null,
            true,
            LocationSize.unexplorable,
            false,
            true,
            false,
            false,
            false,
            false,
            false,
            false,
            Array.Empty<Tag>(),
            new[] { Service.ships }
        ),
        new LocationType(
            "port",
            Rarity.epic,
            null,
            true,
            LocationSize.unexplorable,
            false,
            true,
            false,
            false,
            false,
            false,
            false,
            false,
            Array.Empty<Tag>(),
            new[] { Service.ships }
        ),
        new LocationType(
            "sewer",
            Rarity.rare,
            null,
            true,
            LocationSize.large,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            Array.Empty<Tag>(),
            Array.Empty<Service>()
        ),
        new LocationType(
            "shop",
            Rarity.common,
            null,
            true,
            LocationSize.unexplorable,
            true,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            new[]
            {
                new Tag("Snack", TagType.food),
                new Tag("Light Armor", TagType.armor),
                new Tag("Light Weapon", TagType.weapon),
                new Tag("Ammunition", TagType.weapon),
                new Tag("Adventure Gear", TagType.generalGoods),
                new Tag("Tools", TagType.generalGoods),
            },
            Array.Empty<Service>()
        ),
        new LocationType(
            "shrine",
            Rarity.uncommon,
            null,
            true,
            LocationSize.unexplorable,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            Array.Empty<Tag>(),
            new[] { Service.healing }
        ),
        new LocationType(
            "temple",
            Rarity.rare,
            null,
            true,
            LocationSize.unexplorable,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            Array.Empty<Tag>(),
            new[] { Service.healing }
        )
    };
}
