namespace DolCon.Models;

using Enums;

public record LocationType(
    string Type,
    Rarity Rarity,
    Rarity MaxRarity,
    int? Biome,
    bool IsBurgLocation,
    LocationSize Size,
    bool AllowMultiple,
    bool NeedsPort,
    bool NeedsCitadel,
    bool NeedsPlaza,
    bool NeedsShanty,
    bool NeedsTemple,
    bool NeedsWalls,
    bool NeedsCityOfLight,
    bool isWild,
    Tag[] Goods,
    ServiceType[] Services
);

public static class LocationTypes
{
    public static List<LocationType> Types { get; } = new()
    {
        new LocationType(
            "abandoned mine",
            Rarity.uncommon,
            Rarity.uncommon,
            null,
            false,
            LocationSize.medium,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            true,
            Array.Empty<Tag>(),
            Array.Empty<ServiceType>()
        ),
        new LocationType(
            "abandoned temple",
            Rarity.rare,
            Rarity.rare,
            null,
            false,
            LocationSize.small,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            true,
            Array.Empty<Tag>(),
            Array.Empty<ServiceType>()
        ),
        new LocationType(
            "abandoned wizard tower",
            Rarity.epic,
            Rarity.epic,
            null,
            false,
            LocationSize.medium,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            true,
            Array.Empty<Tag>(),
            Array.Empty<ServiceType>()
        ),
        new LocationType(
            "ancient battlefield",
            Rarity.epic,
            Rarity.epic,
            null,
            false,
            LocationSize.medium,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            true,
            Array.Empty<Tag>(),
            Array.Empty<ServiceType>()
        ),
        new LocationType(
            "ruins",
            Rarity.uncommon,
            Rarity.uncommon,
            null,
            false,
            LocationSize.medium,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            true,
            Array.Empty<Tag>(),
            Array.Empty<ServiceType>()
        ),
        new LocationType(
            "ancient tomb",
            Rarity.rare,
            Rarity.rare,
            null,
            false,
            LocationSize.medium,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            true,
            Array.Empty<Tag>(),
            Array.Empty<ServiceType>()
        ),
        new LocationType(
            "arena",
            Rarity.uncommon,
            Rarity.uncommon,
            null,
            true,
            LocationSize.unexplorable,
            false,
            false,
            false,
            true,
            false,
            false,
            false,
            false,
            false,
            Array.Empty<Tag>(),
            new[] { ServiceType.Combat, ServiceType.Entertainment }
        ),
        new LocationType(
            "armory",
            Rarity.uncommon,
            Rarity.epic,
            null,
            true,
            LocationSize.unexplorable,
            true,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            new[]
            {
                new Tag("Light Armor", TagType.Armor),
                new Tag("Medium Armor", TagType.Armor),
                new Tag("Heavy Armor", TagType.Armor),
                new Tag("Shield", TagType.Armor),
                new Tag("Light Weapon", TagType.Weapon),
                new Tag("Medium Weapon", TagType.Weapon),
                new Tag("Heavy Weapon", TagType.Weapon),
                new Tag("Ammunition", TagType.Weapon),
            },
            new[] { ServiceType.Repair }
        ),
        new LocationType(
            "bandit camp",
            Rarity.rare,
            Rarity.rare,
            null,
            false,
            LocationSize.small,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            Array.Empty<Tag>(),
            Array.Empty<ServiceType>()
        ),
        new LocationType(
            "tavern",
            Rarity.common,
            Rarity.rare,
            null,
            true,
            LocationSize.unexplorable,
            true,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            new[]
            {
                new Tag("Snack", TagType.Food),
                new Tag("Meal", TagType.Food),
                new Tag("Spirits", TagType.Food)
            },
            new[] { ServiceType.Drinks, ServiceType.Food }
        ),
        new LocationType(
            "blacksmith",
            Rarity.uncommon,
            Rarity.legendary,
            null,
            true,
            LocationSize.unexplorable,
            true,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            Array.Empty<Tag>(),
            new[] { ServiceType.Repair, ServiceType.Upgrade }
        ),
        new LocationType(
            "manor",
            Rarity.rare,
            Rarity.rare,
            null,
            true,
            LocationSize.small,
            false,
            false,
            true,
            false,
            false,
            false,
            false,
            false,
            false,
            Array.Empty<Tag>(),
            Array.Empty<ServiceType>()
        ),
        new LocationType(
            "castle",
            Rarity.rare,
            Rarity.rare,
            null,
            true,
            LocationSize.medium,
            false,
            false,
            true,
            false,
            false,
            false,
            false,
            false,
            false,
            Array.Empty<Tag>(),
            Array.Empty<ServiceType>()
        ),
        new LocationType(
            "fortress",
            Rarity.epic,
            Rarity.epic,
            null,
            true,
            LocationSize.large,
            false,
            false,
            true,
            false,
            false,
            false,
            false,
            false,
            false,
            Array.Empty<Tag>(),
            Array.Empty<ServiceType>()
        ),
        new LocationType(
            "citadel",
            Rarity.legendary,
            Rarity.legendary,
            null,
            true,
            LocationSize.huge,
            false,
            false,
            true,
            false,
            false,
            false,
            false,
            false,
            false,
            Array.Empty<Tag>(),
            Array.Empty<ServiceType>()
        ),
        new LocationType(
            "cave",
            Rarity.uncommon,
            Rarity.uncommon,
            null,
            false,
            LocationSize.large,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            true,
            Array.Empty<Tag>(),
            Array.Empty<ServiceType>()
        ),
        new LocationType(
            "cemetery",
            Rarity.uncommon,
            Rarity.uncommon,
            null,
            true,
            LocationSize.medium,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            Array.Empty<Tag>(),
            Array.Empty<ServiceType>()
        ),
        new LocationType(
            "colosseum",
            Rarity.epic,
            Rarity.epic,
            null,
            true,
            LocationSize.unexplorable,
            false,
            false,
            false,
            true,
            false,
            false,
            false,
            false,
            false,
            Array.Empty<Tag>(),
            new[] { ServiceType.Combat, ServiceType.Entertainment }
        ),
        new LocationType(
            "crypt",
            Rarity.rare,
            Rarity.rare,
            null,
            false,
            LocationSize.large,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            Array.Empty<Tag>(),
            Array.Empty<ServiceType>()
        ),
        new LocationType(
            "dungeon",
            Rarity.rare,
            Rarity.rare,
            null,
            true,
            LocationSize.large,
            false,
            false,
            false,
            false,
            true,
            false,
            true,
            false,
            false,
            Array.Empty<Tag>(),
            Array.Empty<ServiceType>()
        ),
        new LocationType(
            "farm",
            Rarity.common,
            Rarity.common,
            null,
            false,
            LocationSize.unexplorable,
            true,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            new[]
            {
                new Tag("Snack", TagType.Food),
            },
            new[] { ServiceType.Food }
        ),
        new LocationType(
            "fort",
            Rarity.rare,
            Rarity.rare,
            null,
            false,
            LocationSize.medium,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            Array.Empty<Tag>(),
            new[] { ServiceType.Food, ServiceType.Combat, ServiceType.Lodging, ServiceType.Repair }
        ),
        new LocationType(
            "garden",
            Rarity.uncommon,
            Rarity.rare,
            null,
            true,
            LocationSize.small,
            false,
            false,
            false,
            true,
            false,
            false,
            false,
            false,
            false,
            new[]
            {
                new Tag("Snack", TagType.Food),
                new Tag("Meal", TagType.Food),
            },
            new[] { ServiceType.Food }
        ),
        new LocationType(
            "general store",
            Rarity.common,
            Rarity.rare,
            null,
            true,
            LocationSize.unexplorable,
            true,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            new[]
            {
                new Tag("Snack", TagType.Food),
                new Tag("Light Armor", TagType.Armor),
                new Tag("Light Weapon", TagType.Weapon),
                new Tag("Ammunition", TagType.Weapon),
                new Tag("Adventure Gear", TagType.GeneralGoods),
                new Tag("Tools", TagType.GeneralGoods),
            },
            Array.Empty<ServiceType>()
        ),
        new LocationType(
            "inn",
            Rarity.uncommon,
            Rarity.epic,
            null,
            true,
            LocationSize.unexplorable,
            true,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            new[]
            {
                new Tag("Snack", TagType.Food),
                new Tag("Meal", TagType.Food),
                new Tag("Spirits", TagType.Food)
            },
            new[] { ServiceType.Food, ServiceType.Lodging }
        ),
        new LocationType(
            "library",
            Rarity.rare,
            Rarity.legendary,
            null,
            true,
            LocationSize.small,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            Array.Empty<Tag>(),
            Array.Empty<ServiceType>()
        ),
        new LocationType(
            "mine",
            Rarity.uncommon,
            Rarity.uncommon,
            null,
            false,
            LocationSize.large,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            Array.Empty<Tag>(),
            Array.Empty<ServiceType>()
        ),
        new LocationType(
            "pier",
            Rarity.common,
            Rarity.common,
            null,
            true,
            LocationSize.unexplorable,
            false,
            true,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            Array.Empty<Tag>(),
            new[] { ServiceType.Ships }
        ),
        new LocationType(
            "dock",
            Rarity.uncommon,
            Rarity.uncommon,
            null,
            true,
            LocationSize.unexplorable,
            false,
            true,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            Array.Empty<Tag>(),
            new[] { ServiceType.Ships }
        ),
        new LocationType(
            "harbor",
            Rarity.rare,
            Rarity.rare,
            null,
            true,
            LocationSize.unexplorable,
            false,
            true,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            Array.Empty<Tag>(),
            new[] { ServiceType.Ships }
        ),
        new LocationType(
            "port",
            Rarity.epic,
            Rarity.epic,
            null,
            true,
            LocationSize.unexplorable,
            false,
            true,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            Array.Empty<Tag>(),
            new[] { ServiceType.Ships }
        ),
        new LocationType(
            "sewer",
            Rarity.rare,
            Rarity.rare,
            null,
            true,
            LocationSize.large,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            Array.Empty<Tag>(),
            Array.Empty<ServiceType>()
        ),
        new LocationType(
            "shrine",
            Rarity.uncommon,
            Rarity.uncommon,
            null,
            true,
            LocationSize.unexplorable,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            Array.Empty<Tag>(),
            new[] { ServiceType.Healing }
        ),
        new LocationType(
            "temple",
            Rarity.rare,
            Rarity.rare,
            null,
            true,
            LocationSize.unexplorable,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            Array.Empty<Tag>(),
            new[] { ServiceType.Healing }
        ),
        new LocationType(
            "basilica",
            Rarity.epic,
            Rarity.epic,
            null,
            true,
            LocationSize.unexplorable,
            false,
            false,
            false,
            false,
            false,
            true,
            false,
            false,
            false,
            Array.Empty<Tag>(),
            new[] { ServiceType.Healing, ServiceType.Lodging }
        ),
        new LocationType(
            "The Citadel of Eternity",
            Rarity.legendary,
            Rarity.legendary,
            null,
            true,
            LocationSize.unexplorable,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            true,
            false,
            Array.Empty<Tag>(),
            new[] { ServiceType.Healing }
        ),
        new LocationType(
            "The Cave of Life",
            Rarity.legendary,
            Rarity.legendary,
            null,
            true,
            LocationSize.unexplorable,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            true,
            false,
            Array.Empty<Tag>(),
            Array.Empty<ServiceType>()
        ),
        new LocationType(
            "The Conclave's Tower",
            Rarity.legendary,
            Rarity.legendary,
            null,
            true,
            LocationSize.unexplorable,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            true,
            false,
            Array.Empty<Tag>(),
            Array.Empty<ServiceType>()
        ),
        new LocationType(
            "The University",
            Rarity.legendary,
            Rarity.legendary,
            null,
            true,
            LocationSize.unexplorable,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            true,
            false,
            Array.Empty<Tag>(),
            Array.Empty<ServiceType>()
        ),
        new LocationType(
            "The Knight's Barracks",
            Rarity.legendary,
            Rarity.legendary,
            null,
            true,
            LocationSize.unexplorable,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            true,
            false,
            Array.Empty<Tag>(),
            new[] { ServiceType.Lodging, ServiceType.Food, ServiceType.Combat }
        ),
        new LocationType(
            "The Paladin's Fortress",
            Rarity.legendary,
            Rarity.legendary,
            null,
            true,
            LocationSize.unexplorable,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            true,
            false,
            Array.Empty<Tag>(),
            new[] { ServiceType.Lodging, ServiceType.Healing, ServiceType.Food, ServiceType.Drinks, ServiceType.Combat }
        ),
        new LocationType(
            "The Paladin's Forge",
            Rarity.legendary,
            Rarity.legendary,
            null,
            true,
            LocationSize.unexplorable,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            true,
            false,
            new[]
            {
                new Tag("Light Armor", TagType.Armor),
                new Tag("Medium Armor", TagType.Armor),
                new Tag("Heavy Armor", TagType.Armor),
                new Tag("Shield", TagType.Armor),
                new Tag("Light Weapon", TagType.Weapon),
                new Tag("Medium Weapon", TagType.Weapon),
                new Tag("Heavy Weapon", TagType.Weapon),
                new Tag("Ammunition", TagType.Weapon)
            },
            new[] { ServiceType.Repair, ServiceType.Upgrade }
        ),
        new LocationType(
            "The Judicator's Court",
            Rarity.legendary,
            Rarity.legendary,
            null,
            true,
            LocationSize.unexplorable,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            true,
            false,
            Array.Empty<Tag>(),
            Array.Empty<ServiceType>()
        ),
        new LocationType(
            "The Hall of Penitence",
            Rarity.legendary,
            Rarity.legendary,
            null,
            true,
            LocationSize.large,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            true,
            false,
            Array.Empty<Tag>(),
            Array.Empty<ServiceType>()
        ),
        new LocationType(
            "The Sky Temple",
            Rarity.legendary,
            Rarity.legendary,
            null,
            true,
            LocationSize.unexplorable,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            true,
            false,
            Array.Empty<Tag>(),
            Array.Empty<ServiceType>()
        ),
        new LocationType(
            "hamlet with a shrine",
            Rarity.uncommon,
            Rarity.uncommon,
            null,
            false,
            LocationSize.unexplorable,
            true,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            Array.Empty<Tag>(),
            new[] { ServiceType.Healing }
        ),
        new LocationType(
            "hamlet",
            Rarity.common,
            Rarity.common,
            null,
            false,
            LocationSize.unexplorable,
            true,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            Array.Empty<Tag>(),
            Array.Empty<ServiceType>()
        ),
        new LocationType(
            "hamlet with a tavern",
            Rarity.common,
            Rarity.common,
            null,
            false,
            LocationSize.unexplorable,
            true,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            Array.Empty<Tag>(),
            new[] { ServiceType.Food, ServiceType.Drinks }
        ),
        new LocationType(
            "roadhouse",
            Rarity.rare,
            Rarity.rare,
            null,
            false,
            LocationSize.unexplorable,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            Array.Empty<Tag>(),
            new[] { ServiceType.Food, ServiceType.Drinks, ServiceType.Lodging }
        )
    };
}
